### ISSUE TITLE
Bug: leaving midgame causes an exception

### ISSUE THREAD

**Issue by Sylensky** [Ajneb97/PaintballBattle#5]
`/pb leave` during a ongoing game throws an exception on latest mc version.
mc: git-Paper-136 (MC: 1.18.1)
```
[22:41:53 INFO]: Sylensky issued server command: /pb leave
> 
[22:41:53 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pb' in plugin PaintballBattle v1.7.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2285) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2096) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2077) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-136]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:322) ~[?:?]
	at pb.ajneb97.utils.UtilidadesOtros.getNumeroAleatorio(UtilidadesOtros.java:65) ~[PaintballBattle.jar:?]
	at pb.ajneb97.managers.PartidaManager.ejecutarComandosRewards(PartidaManager.java:694) ~[PaintballBattle.jar:?]
	at pb.ajneb97.managers.PartidaManager.iniciarFaseFinalizacion(PartidaManager.java:654) ~[PaintballBattle.jar:?]
	at pb.ajneb97.managers.PartidaManager.jugadorSale(PartidaManager.java:168) ~[PaintballBattle.jar:?]
	at pb.ajneb97.Comando.onCommand(Comando.java:192) ~[PaintballBattle.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 21 more
```

**Comment by Ajneb97** [comment]
You are using an incorrect reward command. Show me the config of that.

**Comment by Sylensky** [comment]
i am using this config. https://pastebin.com/8SBZtM2C

**Comment by Sylensky** [comment]
ah i might see the problem. checking if the issue is still there with the default command.

**Comment by Sylensky** [comment]
i was indeed using a wrong reward command.
